version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: src/SelfFinanceApp.Api/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=selffinancedb;Username=postgres;Password=mysecretpassword;Include Error Detail=true
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: selffinance-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=selffinancedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
 
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 13133:13133
      - 4317:4317
      - 4318:4318
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: