// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SelfFinanceApp.Persistance.DatabaseContext;

#nullable disable

namespace SelfFinanceApp.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250612073442_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SelfFinanceApp.Domain.Aggregates.FinancialOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FinanceTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FinanceTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FinancialOperations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            DateCreated = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Paying bills 06-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            DateCreated = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Paying rent 06-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            DateCreated = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Salary 06-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            DateCreated = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Dividend 06-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            DateCreated = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Paying bills 07-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            DateCreated = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Paying rent 07-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            DateCreated = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Salary 07-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            DateCreated = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Dividend 07-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            DateCreated = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Paying bills 08-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            DateCreated = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Paying rent 08-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            DateCreated = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Salary 08-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            DateCreated = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Dividend 08-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            DateCreated = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Paying bills 09-2023"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            DateCreated = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinanceTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Paying rent 09-2023"
                        });
                });

            modelBuilder.Entity("SelfFinanceApp.Domain.Entities.FinancialType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FinancialTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateCreated = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bills",
                            TransactionType = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DateCreated = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rent",
                            TransactionType = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DateCreated = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Salary",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DateCreated = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dividends",
                            TransactionType = 1
                        });
                });

            modelBuilder.Entity("SelfFinanceApp.Domain.Aggregates.FinancialOperation", b =>
                {
                    b.HasOne("SelfFinanceApp.Domain.Entities.FinancialType", "FinanceType")
                        .WithMany("FinancialOperations")
                        .HasForeignKey("FinanceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SelfFinanceApp.Domain.ValueObjects.MonetaryValue", "Money", b1 =>
                        {
                            b1.Property<Guid>("FinancialOperationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("FinancialOperationId");

                            b1.ToTable("FinancialOperations");

                            b1.WithOwner()
                                .HasForeignKey("FinancialOperationId");

                            b1.HasData(
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-000000000001"),
                                    Amount = 1000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-000000000002"),
                                    Amount = 1000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-000000000003"),
                                    Amount = 3000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-000000000004"),
                                    Amount = 100m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-000000000005"),
                                    Amount = 1000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-000000000006"),
                                    Amount = 1000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-000000000007"),
                                    Amount = 3000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-000000000008"),
                                    Amount = 100m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-000000000009"),
                                    Amount = 1000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-00000000000a"),
                                    Amount = 1000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-00000000000b"),
                                    Amount = 3000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-00000000000c"),
                                    Amount = 100m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-00000000000d"),
                                    Amount = 1000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    FinancialOperationId = new Guid("10000000-0000-0000-0000-00000000000e"),
                                    Amount = 1000m,
                                    Currency = "EUR"
                                });
                        });

                    b.Navigation("FinanceType");

                    b.Navigation("Money");
                });

            modelBuilder.Entity("SelfFinanceApp.Domain.Entities.FinancialType", b =>
                {
                    b.Navigation("FinancialOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
