version: '3.9'
volumes:
  postgres-data:
  
services:
  db:
    image: postgres:latest
    container_name: MyPostgresDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@word
      - POSTGRES_DB=SelfFinanceApp
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data